#!/usr/bin/env bash

rm -rf test-tree
mkdir -p test-tree/1-simple/{1,2,3,4,5,^,$,^$,$^}
mkdir -p test-tree/2-negation/{10,20,30,40,50}
mkdir -p test-tree/3-wildcards/{{foo,bar}.html,html/{foo,bar}.html}
mkdir -p test-tree/4-escapes/{{*,o{,_,__,?,}ther}.html,other.html{,\$,\$\$}}
